#pragma once

class CGameSettings
{
public:

	static float GetObstacleSpeed(int depth);

	// SOUND VOLUME
	
	static float	VOLUME_MUSIC_GAME_OVER;
	
	static float	VOLUME_PLAYER_MINIGUN_SHOOT;
	static float	VOLUME_PLAYER_MINIGUN_TURN;
	static float	VOLUME_PLAYER_CANNON;
	static float	VOLUME_PLAYER_BLAST;
	static float	VOLUME_PLAYER_VELOCITY_AFTERBURN;

	static float	VOLUME_ENEMY_SHOOT_ROLLER;

	static float	VOLUME_BOSS_SCATTER;
	static float	VOLUME_BOSS_LASER;
	static float	VOLUME_BOSS_CANNON;
	
	static float	VOLUME_BOSS_CHAIN_EXPLOSION_MIN;
	static float	VOLUME_BOSS_CHAIN_EXPLOSION_MAX;

	// BACKGROUND SCROLLING

	static float	SCROLLING_PLAYER_VELOCITY_MAX;

	static float	SCROLLING_BACKGROUND_TOP_MIN;
	static float	SCROLLING_BACKGROUND_TOP_MAX;

	static float	SCROLLING_EXPLOSION_MIN;
	static float	SCROLLING_EXPLOSION_MAX;

	// EXTRA LIFE

	static float	EXTRA_LIFE_SCORE;
	static float	EXTRA_LIFE_MULTIPLIER;

	// EXTRA BLAST

	static float	EXTRA_BLAST_SCORE;
	static float	EXTRA_BLAST_MULTIPLIER;

	// PLAYER

	static int		PLAYER_LIVES;
	static int		PLAYER_HEALTH;
	static float	PLAYER_WIDTH;
	static float	PLAYER_HEIGHT;
	static float	PLAYER_SPEED;
	static float	PLAYER_MAX_VELOCITY;

	static int		PLAYER_CANNON_ENERGY_MAX;
	static int		PLAYER_CANNON_DAMAGE;
	static float	PLAYER_CANNON_SPEED;
	static float	PLAYER_CANNON_TIMER;

	static float	PLAYER_BLAST_ACTIVE_DURATION;
	static float	PLAYER_BLAST_BEAM_DURATION;
	static int		PLAYER_BLAST_BEAM_COUNT;

	static int		PLAYER_BLAST_DAMAGE;
	static int		PLAYER_BLAST_AMOUNT;

	static float	PLAYER_SHIP_ENTER_POS_X;
	static float	PLAYER_SHIP_ENTER_POS_Y;
	static float	PLAYER_SHIP_START_POS_Y;

	// WEAPONS

	static float	PLAYER_BULLET_WIDTH;
	static float	PLAYER_BULLET_HEIGHT;
	
	static float	ENEMY_DRONE_BULLET_WIDTH;
	static float	ENEMY_DRONE_BULLET_HEIGHT;
	static float	ENEMY_DRONE_BULLET_SPEED;
	static int		ENEMY_DRONE_BULLET_DAMAGE;
	static int		ENEMY_DRONE_SHIP_DAMAGE;

	static float	ENEMY_SNIPER_BULLET_WIDTH;
	static float	ENEMY_SNIPER_BULLET_HEIGHT;
	static float	ENEMY_SNIPER_BULLET_SPEED;
	static int		ENEMY_SNIPER_BULLET_DAMAGE;
	static int		ENEMY_SNIPER_SHIP_DAMAGE;

	static float	ENEMY_ROLLER_BULLET_WIDTH;
	static float	ENEMY_ROLLER_BULLET_HEIGHT;
	static float	ENEMY_ROLLER_BULLET_SPEED;
	static int		ENEMY_ROLLER_BULLET_DAMAGE;
	static int		ENEMY_ROLLER_SHIP_DAMAGE;

	static float	ENEMY_GUARD_BULLET_WIDTH;
	static float	ENEMY_GUARD_BULLET_HEIGHT;
	static float	ENEMY_GUARD_BULLET_SPEED;
	static int		ENEMY_GUARD_BULLET_DAMAGE;
	static int		ENEMY_GUARD_SHIP_DAMAGE;

	static float	ENEMY_BOSS_LASER_BULLET_WIDTH;
	static float	ENEMY_BOSS_LASER_BULLET_HEIGHT;
	static float	ENEMY_BOSS_LASER_BULLET_SPEED;
	static int		ENEMY_BOSS_LASER_BULLET_DAMAGE;
	
	static float	ENEMY_BOSS_SCATTER_BULLET_WIDTH;
	static float	ENEMY_BOSS_SCATTER_BULLET_HEIGHT;
	static float	ENEMY_BOSS_SCATTER_BULLET_SPEED;
	static int		ENEMY_BOSS_SCATTER_BULLET_DAMAGE;

	static float	ENEMY_BOSS_CANNON_BULLET_SPEED;
	static int		ENEMY_BOSS_CANNON_BULLET_DAMAGE;

	// ENEMIES

	static int		ENEMY_DRONE_HEALTH;
	static float	ENEMY_DRONE_WIDTH;
	static float	ENEMY_DRONE_HEIGHT;
	static float	ENEMY_DRONE_LAUNCH_SPEED;
	static float	ENEMY_DRONE_LAUNCH_SHOOT_TIME;
	static float	ENEMY_DRONE_STRIKE_SPEED;
	static float	ENEMY_DRONE_STRIKE_SHOOT_TIME;
	static float	ENEMY_DRONE_ENTER_DURATION;
	static float	ENEMY_DRONE_FLEE_DURATION;

	static int		ENEMY_SNIPER_HEALTH;
	static float	ENEMY_SNIPER_WIDTH;
	static float	ENEMY_SNIPER_HEIGHT;
	static float	ENEMY_SNIPER_LAUNCH_SPEED;
	static float	ENEMY_SNIPER_LAUNCH_SHOOT_TIME;
	static float	ENEMY_SNIPER_STRIKE_SPEED;
	static float	ENEMY_SNIPER_STRIKE_SHOOT_TIME;
	static float	ENEMY_SNIPER_ENTER_DURATION;
	static float	ENEMY_SNIPER_FLEE_DURATION;

	static int		ENEMY_ROLLER_HEALTH;
	static float	ENEMY_ROLLER_WIDTH;
	static float	ENEMY_ROLLER_HEIGHT;
	static float	ENEMY_ROLLER_LAUNCH_SPEED;
	static float	ENEMY_ROLLER_LAUNCH_SHOOT_TIME;
	static float	ENEMY_ROLLER_STRIKE_SPEED;
	static float	ENEMY_ROLLER_STRIKE_SHOOT_TIME;
	static float	ENEMY_ROLLER_ENTER_DURATION;
	static float	ENEMY_ROLLER_FLEE_DURATION;

	static int		ENEMY_GUARD_HEALTH;
	static float	ENEMY_GUARD_WIDTH;
	static float	ENEMY_GUARD_HEIGHT;
	static float	ENEMY_GUARD_LAUNCH_SPEED;
	static float	ENEMY_GUARD_LAUNCH_SHOOT_TIME;
	static float	ENEMY_GUARD_STRIKE_SPEED;
	static float	ENEMY_GUARD_STRIKE_SHOOT_TIME;
	static float	ENEMY_GUARD_ENTER_DURATION;
	static float	ENEMY_GUARD_FLEE_DURATION;

	static float	ENEMY_STRIKE_SPEED_MULTIPLIER_MIN;
	static float	ENEMY_STRIKE_SPEED_MULTIPLIER_MAX;

	// BOSSES

	static float	BOSS_WARNING_START_TIME;
	static float	BOSS_WARNING_END_TIME;

	static float	ENEMY_BOSS_FRAME_WIDTH;
	static float	ENEMY_BOSS_FRAME_HEIGHT;
	static int		ENEMY_BOSS_FRAME_HEALTH;
	static float	ENEMY_BOSS_FRAME_SPEED;
	static float	ENEMY_BOSS_FRAME_SHOOT_TIME;

	static float	ENEMY_BOSS_LASER_WIDTH;
	static float	ENEMY_BOSS_LASER_HEIGHT;
	static int		ENEMY_BOSS_LASER_HEALTH;

	static float	ENEMY_BOSS_SCATTER_WIDTH;
	static float	ENEMY_BOSS_SCATTER_HEIGHT;
	static int		ENEMY_BOSS_SCATTER_HEALTH;
	static float	ENEMY_BOSS_SCATTER_SPEED;
	static float	ENEMY_BOSS_SCATTER_SHOOT_TIME;
	static int		ENEMY_BOSS_SCATTER_SHOOT_AMOUNT_MAX;

	static float	ENEMY_BOSS_CANNON_SHOOT_TIME;

	// OBSTACLES

	static float	BIG_ASTEROID_WIDTH;
	static float	BIG_ASTEROID_HEIGHT;

	static float	MEDIUM_ASTEROID_WIDTH;
	static float	MEDIUM_ASTEROID_HEIGHT;

	static float	SMALL_ASTEROID_WIDTH;
	static float	SMALL_ASTEROID_HEIGHT;

	static float	OSTACLE_SPEED_DEPTH_1;
	static float	OSTACLE_SPEED_DEPTH_2;
	static float	OSTACLE_SPEED_DEPTH_3;
	static float	OSTACLE_SPEED_DEPTH_4;
	static float	OSTACLE_SPEED_DEPTH_5;

	// SHIPS COMMON VALUES

	static float	SHIP_AFTERBURN_FLICKER_SHOW_DURATION;
	static float	SHIP_AFTERBURN_FLICKER_HIDE_DURATION;

	// UI ELEMENTS

	static float	UI_NUMBER_WIDTH;
	static float	UI_NUMBER_HEIGHT;

	static int		UI_PLAYER_LIVES_BASE_POS_X;
	static int		UI_PLAYER_LIVES_BASE_POS_Y;
	static int		UI_PLAYER_LIVES_NUMBER_POS_X;
	static int		UI_PLAYER_LIVES_NUMBER_POS_Y;

	static int		UI_PLAYER_BLAST_BASE_POS_X;
	static int		UI_PLAYER_BLAST_BASE_POS_Y;
	static int		UI_PLAYER_BLAST_NUMBER_POS_X;
	static int		UI_PLAYER_BLAST_NUMBER_POS_Y;

	static int		UI_PLAYER_HEALTH_BAR_POS_X;
	static int		UI_PLAYER_HEALTH_BAR_POS_Y;
	static int		UI_PLAYER_HEALTH_FILL_POS_X;
	static int		UI_PLAYER_HEALTH_FILL_POS_Y;

	static int		UI_PLAYER_CANNON_BAR_POS_X;
	static int		UI_PLAYER_CANNON_BAR_POS_Y;
	static int		UI_PLAYER_CANNON_FILL_POS_X;
	static int		UI_PLAYER_CANNON_FILL_POS_Y;

	static float	UI_LEVEL_TITLE_APPEAR_DURATION;
	static float	UI_LEVEL_TITLE_STAY_DURATION;
	static float	UI_LEVEL_TITLE_DISAPPEAR_DURATION;

	// EXTRA VISUAL EFFECTS

	static bool		EFFECT_PLAYER_BLAST_LIGHT;
};